In [81]:
import pandas as pd
import numpy as np

### Load dataset

In [146]:
df = pd.read_csv('data/BoardingData.csv', sep=';')

In [148]:
df.head()

,PassengerFirstName,PassengerSecondName,PassengerLastName,PassengerSex,PassengerBirthDate,PassengerDocument,BookingCode,TicketNumber,Baggage,FlightDate,FlightTime,FlightNumber,CodeShare,Destination
0,SAVELII,VIKTOROVICH,RUSANOV,Male,03/10/1983,2879 096860,FRNINO,6625956945991971,Transit,2017-03-22,06:05,SU1369,Own,Moscow
1,LEV,MARKOVICH,ISAEV,Male,12/13/1975,1788 173211,Not presented,1643715499224676,Registered,2017-03-18,22:10,SU1180,Own,Volgograd
2,NIKOLAI,I.,NIKOLSKII,Male,12/26/1990,4396 926588,VWNYGF,6247422701565929,Transit,2017-03-18,22:10,SU1180,Own,Volgograd
3,ANATOLII,PETROVICH,SHILOV,Male,05/24/1997,2595 919752,WQFFUE,Not presented,Registered,2017-03-18,22:10,SU1180,Own,Volgograd
4,MIROSLAVA,VIACHESLAVOVNA,SEMENOVA,Female,01/31/1976,6775 516990,Not presented,Not presented,Registered,2017-03-12,11:45,SU6284,Own,Moscow

### Создаем поле для каждого полета

In [149]:
df['FlightNumber_by_date'] = df['FlightNumber'] + ' ' + df['FlightDate'] + ' ' + df['FlightTime']

### Фильтруем только мужчин

In [132]:
df = df[df['PassengerSex'] == 'Male']
df.head()

,PassengerFirstName,PassengerSecondName,PassengerLastName,PassengerSex,PassengerBirthDate,PassengerDocument,BookingCode,TicketNumber,Baggage,FlightDate,FlightTime,FlightNumber,CodeShare,Destination,FlightNumber_by_date
0,SAVELII,VIKTOROVICH,RUSANOV,Male,03/10/1983,2879 096860,FRNINO,6625956945991971,Transit,2017-03-22,06:05,SU1369,Own,Moscow,SU1369 2017-03-22 06:05
1,LEV,MARKOVICH,ISAEV,Male,12/13/1975,1788 173211,Not presented,1643715499224676,Registered,2017-03-18,22:10,SU1180,Own,Volgograd,SU1180 2017-03-18 22:10
2,NIKOLAI,I.,NIKOLSKII,Male,12/26/1990,4396 926588,VWNYGF,6247422701565929,Transit,2017-03-18,22:10,SU1180,Own,Volgograd,SU1180 2017-03-18 22:10
3,ANATOLII,PETROVICH,SHILOV,Male,05/24/1997,2595 919752,WQFFUE,Not presented,Registered,2017-03-18,22:10,SU1180,Own,Volgograd,SU1180 2017-03-18 22:10
5,ARTEM,EDUARDOVICH,KAPUSTIN,Male,10/24/1982,0058 142289,JJADFB,7467749130398378,Transit,2017-03-12,11:45,SU6284,Own,Moscow,SU6284 2017-03-12 11:45

### Создаем список полетов для каждого пассажира

In [117]:
passenger_flights = {}

for index, row in df[['PassengerDocument', 'FlightNumber_by_date']].iterrows():
    document = row['PassengerDocument']
    flight_number = row['FlightNumber_by_date']
    
    if not document in passenger_flights:
        passenger_flights[document] = []
    passenger_flights[document].append(flight_number)
        
passenger_flights

{'2879 096860': ['SU1369 2017-03-22 06:05', 'SU1364 2017-02-17 16:30'],
 '1788 173211': ['SU1180 2017-03-18 22:10',
  'SU1703 2017-03-02 14:00',
  'SU5603 2017-01-19 08:00'],
 '4396 926588': ['SU1180 2017-03-18 22:10',
  'SU5617 2017-07-03 09:45',
  'SU1142 2017-03-04 13:45',
  'SU1246 2017-04-22 06:00',
  'SU5616 2017-07-12 03:00',
  'SU6286 2017-07-27 16:30',
  'SU6285 2017-06-19 19:25'],
 '2595 919752': ['SU1180 2017-03-18 22:10',
  'SU1465 2017-06-21 16:40',
  'SU1183 2017-04-12 18:20'],
 '0058 142289': ['SU6284 2017-03-12 11:45',
  'SU5619 2017-05-28 00:10',
  'SU6287 2017-05-22 17:40',
  'SU5616 2017-06-07 03:00'],
 '0078 271703': ['SU1281 2017-07-29 14:15',
  'SU5652 2017-04-13 21:40',
  'SU5685 2017-03-28 16:45',
  'SU1270 2017-07-17 05:55',
  'SU1194 2017-06-27 17:05',
  'SU1235 2017-02-04 06:25'],
 '0595 142701': ['SU1482 2017-04-07 00:15', 'SU1337 2017-02-25 21:10'],
 '5057 285380': ['SU1450 2017-02-14 20:20',
  'SU1003 2017-01-04 12:45',
  'SU1410 2017-12-04 05:40',
  'SU1272 2017-01-10 07:05',
  'SU1534 2017-02-03 14:55',
  'SU1421 2017-02-13 12:50'],
 '6948 339409': ['SU1501 2017-09-30 14:30',
  'SU1508 2017-09-22 00:30',
  'SU1007 2017-08-30 19:55',
  'SU1491 2017-01-04 13:20',
  'SU1006 2017-01-30 16:55'],
 '3521 274082': ['SU5602 2017-01-13 16:35',
  'SU5628 2017-08-30 14:00',
  'SU1166 2017-04-09 00:10',
  'SU1458 2017-04-20 21:30',
  'SU1423 2017-07-21 19:30',
  'SU5629 2017-09-12 17:30',
  'SU1459 2017-04-25 08:05',
  'SU1444 2017-08-26 06:35',
  'SU1731 2017-01-24 13:25',
  'SU1157 2017-04-14 16:00'],
 '6754 245225': ['SU1763 2017-11-17 05:35'],
 '5298 581934': ['SU1513 2017-07-11 07:05',
  'SU1158 2017-04-27 06:30',
  'SU1113 2017-04-25 03:35',
  'SU1479 2017-02-27 09:55',
  'SU1478 2017-02-22 00:10'],
 '6788 402722': ['SU1217 2017-10-01 06:05',
  'SU1254 2017-02-28 07:30',
  'SU1255 2017-03-08 11:10',
  'SU1206 2017-09-14 00:15',
  'SU1491 2017-02-06 13:20'],
 '4559 232845': ['SU6292 2017-03-03 09:20'],
 '6256 996083': ['SU1731 2017-01-21 13:25'],
 '9619 111284': ['SU1108 2017-05-04 01:40'],
 '3668 753452': ['SU1431 2017-03-12 07:05',
  'SU1143 2017-01-15 17:55',
  'SU1432 2017-03-09 09:25'],
 '8272 146614': ['SU1167 2017-03-07 05:00', 'SU6183 2017-03-16 09:55'],
 '8634 167429': ['SU1167 2017-03-07 05:00',
  'SU1503 2017-04-13 04:25',
  'SU1500 2017-04-06 08:20',
  'SU1418 2017-06-11 10:10',
  'SU1437 2017-06-17 12:25',
  'SU1166 2017-03-05 00:10',
  'SU1247 2017-05-14 11:15'],
 '3466 808546': ['SU1431 2017-06-07 07:05',
  'SU1366 2017-04-16 09:35',
  'SU1481 2017-01-12 06:40',
  'SU1365 2017-04-28 19:45',
  'SU1140 2017-02-06 16:20',
  'SU6180 2017-03-05 11:05',
  'SU1058 2017-06-09 14:50'],
 '6951 491742': ['SU1431 2017-06-07 07:05',
  'SU1430 2017-05-14 20:35',
  'SU1410 2017-02-06 05:40'],
 '7230 416183': ['SU1641 2017-02-14 15:20'],
 '3616 692590': ['SU1641 2017-02-14 15:20',
  'SU1762 2017-02-08 21:10',
  'SU1106 2017-03-04 16:30',
  'SU1275 2017-04-08 05:30',
  'SU1247 2017-01-17 11:15'],
 '8663 357259': ['SU1181 2017-11-15 03:10',
  'SU1158 2017-07-03 06:30',
  'SU1247 2017-02-23 11:15',
  'SU1758 2017-10-13 07:55'],
 '9679 942167': ['SU4606 2017-08-17 12:10',
  'SU5618 2017-06-05 05:40',
  'SU1235 2017-01-03 06:25',
  'SU6285 2017-05-10 19:25',
  'SU6169 2017-03-31 00:50',
  'SU1183 2017-02-28 18:20',
  'SU1247 2017-04-20 11:15',
  'SU5615 2017-05-30 14:05',
  'SU4605 2017-07-08 14:20',
  'SU5623 2017-06-29 19:25',
  'SU5620 2017-06-27 09:50'],
 '0834 239198': ['SU5624 2017-03-26 20:20', 'SU6284 2017-04-19 11:45'],
 '4138 361760': ['SU5624 2017-03-26 20:20',
  'SU6292 2017-04-20 09:20',
  'SU5626 2017-02-23 08:10',
  'SU5605 2017-04-19 11:10'],
 '8306 644972': ['SU1261 2017-03-01 23:10',
  'SU1238 2017-02-13 21:45',
  'SU1479 2017-01-22 09:55'],
 '7948 851468': ['SU1261 2017-03-01 23:10',
  'SU1236 2017-02-04 01:55',
  'SU1641 2017-03-09 15:20',
  'SU1762 2017-03-05 21:10'],
 '6468 393450': ['SU1403 2017-09-05 17:25',
  'SU1168 2017-06-07 18:10',
  'SU1501 2017-04-25 14:30',
  'SU1161 2017-06-19 19:10',
  'SU1375 2017-01-05 18:55',
  'SU1506 2017-03-31 13:15'],
 '1412 601525': ['SU1251 2017-01-12 02:50',
  'SU1255 2017-01-15 11:10',
  'SU1369 2017-01-08 06:05'],
 '8295 760019': ['SU1371 2017-01-31 12:35',
  'SU1251 2017-04-11 02:50',
  'SU1413 2017-01-10 13:55',
  'SU1158 2017-02-11 06:30',
  'SU1370 2017-01-19 09:10',
  'SU1251 2017-05-10 02:50'],
 '2595 143278': ['SU1211 2017-04-19 12:35'],
 '8063 081529': ['SU1211 2017-04-19 12:35',
  'SU1238 2017-08-31 21:45',
  'SU1536 2017-01-15 00:20',
  'SU1531 2017-01-31 07:55',
  'SU1214 2017-04-01 16:40',
  'SU1233 2017-01-13 19:15'],
 '5450 688176': ['SU1211 2017-04-19 12:35'],
 '7574 442722': ['SU1009 2017-07-17 03:50',
  'SU1053 2017-02-04 12:20',
  'SU1006 2017-07-08 16:55',
  'SU1485 2017-06-26 09:05'],
 '8329 265263': ['SU1464 2017-06-27 14:20',
  'SU1195 2017-04-03 20:35',
  'SU1367 2017-01-18 12:45',
  'SU1465 2017-07-04 16:40',
  'SU1194 2017-03-19 17:05'],
 '0809 405757': ['SU1248 2017-03-15 14:35', 'SU1513 2017-03-03 07:05'],
 '4779 047867': ['SU1248 2017-03-15 14:35',
  'SU1479 2017-06-03 09:55',
  'SU1478 2017-04-24 00:10'],
 '4405 704644': ['SU1397 2017-01-31 06:05',
  'SU1422 2017-07-24 13:20',
  'SU1445 2017-01-06 19:40',
  'SU1420 2017-10-15 06:30',
  'SU1416 2017-03-01 22:05',
  'SU1417 2017-09-18 06:05',
  'SU1425 2017-11-19 05:55'],
 '9278 702340': ['SU1397 2017-01-31 06:05'],
 '4971 654617': ['SU1397 2017-01-31 06:05'],
 '1803 515259': ['SU1397 2017-01-31 06:05'],
 '0670 684443': ['SU1191 2017-01-02 12:20'],
 '8794 083189': ['SU1191 2017-01-02 12:20',
  'SU1213 2017-04-28 18:05',
  'SU1135 2017-03-17 14:10',
  'SU1604 2017-03-29 09:15',
  'SU1233 2017-09-01 19:15',
  'SU1134 2017-02-21 09:30',
  'SU1157 2017-05-28 16:00'],
 '5460 618335': ['SU1191 2017-01-02 12:20', 'SU5615 2017-06-07 14:05'],
 '6401 005380': ['SU1135 2017-07-20 14:10', 'SU1058 2017-01-08 15:25'],
 '1669 679672': ['SU1443 2017-04-26 09:55', 'SU1562 2017-02-04 00:00'],
 '3823 495710': ['SU1053 2017-02-06 12:20'],
 '8316 706629': ['SU1053 2017-02-06 12:20', 'SU1161 2017-05-01 19:10'],
 '1997 276152': ['SU1053 2017-02-06 12:20',
  'SU1056 2017-01-26 20:55',
  'SU1371 2017-01-19 12:35'],
 '1883 098614': ['SU1053 2017-02-06 12:20',
  'SU6290 2017-01-14 14:30',
  'SU1196 2017-04-06 22:50'],
 '1744 952182': ['SU1459 2017-01-13 08:05'],
 '3194 019242': ['SU1459 2017-01-13 08:05'],
 '5269 297714': ['SU1459 2017-01-13 08:05'],
 '4123 441953': ['SU1459 2017-01-13 08:05'],
 '7288 324460': ['SU1459 2017-01-13 08:05'],
 '0400 782744': ['SU1459 2017-01-13 08:05',
  'SU1436 2017-04-15 07:00',
  'SU1523 2017-06-17 09:35',
  'SU1520 2017-05-10 09:40'],
 '0034 278597': ['SU1459 2017-01-13 08:05'],
 '1088 195567': ['SU1459 2017-01-13 08:05'],
 '9394 302550': ['SU1459 2017-01-13 08:05'],
 '3276 602860': ['SU1459 2017-01-13 08:05',
  'SU1197 2017-03-17 02:45',
  'SU1190 2017-03-06 09:00'],
 '1808 822155': ['SU1459 2017-01-13 08:05', 'SU6180 2017-03-09 11:05'],
 '5524 738294': ['SU1459 2017-01-13 08:05', 'SU1143 2017-05-15 17:55'],
 '6006 653903': ['SU1459 2017-01-13 08:05'],
 '2634 721977': ['SU1459 2017-01-13 08:05'],
 '0735 568732': ['SU1459 2017-01-13 08:05', 'SU1307 2017-05-15 10:15'],
 '8282 250135': ['SU1459 2017-01-13 08:05', 'SU1130 2017-02-19 22:00'],
 '1556 064005': ['SU1459 2017-01-13 08:05'],
 '8026 996881': ['SU1459 2017-01-13 08:05', 'SU1487 2017-01-19 21:35'],
 '8371 986338': ['SU1459 2017-01-13 08:05'],
 '0550 572974': ['SU1459 2017-01-13 08:05',
  'SU1129 2017-04-01 06:20',
  'SU1515 2017-03-02 14:00',
  'SU1514 2017-01-31 07:35'],
 '6252 079751': ['SU1459 2017-01-13 08:05',
  'SU1134 2017-02-24 09:30',
  'SU1121 2017-02-28 15:40'],
 '6735 613581': ['SU1459 2017-01-13 08:05',
  'SU1276 2017-01-31 07:15',
  'SU1219 2017-02-13 06:25'],
 '0803 989712': ['SU1459 2017-01-13 08:05'],
 '2376 391944': ['SU1251 2017-06-16 02:50',
  'SU1703 2017-05-29 14:00',
  'SU1643 2017-02-03 14:00',
  'SU6281 2017-03-20 17:40',
  'SU1251 2017-06-24 02:50',
  'SU1439 2017-03-17 14:15'],
 '3119 061454': ['SU1307 2017-03-22 10:15',
  'SU1643 2017-03-02 14:00',
  'SU1460 2017-03-16 08:20'],
 '3384 131110': ['SU1307 2017-03-22 10:15',
  'SU1278 2017-02-06 20:55',
  'SU1306 2017-03-04 00:05',
  'SU1191 2017-02-24 12:20',
  'SU1144 2017-03-30 17:15',
  'SU1428 2017-01-04 00:55'],
 '3861 090716': ['SU1442 2017-03-24 20:45',
  'SU1193 2017-01-01 18:05',
  'SU1445 2017-04-01 19:40',
  'SU1604 2017-01-08 09:15'],
 '2063 124217': ['SU1362 2017-07-24 16:50',
  'SU1491 2017-01-06 13:20',
  'SU1252 2017-09-22 14:05',
  'SU1255 2017-10-09 11:10',
  'SU1336 2017-11-01 17:20',
  'SU1363 2017-09-15 20:35',
  'SU1423 2017-07-17 19:30'],
 '4963 951772': ['SU1206 2017-02-27 00:15',
  'SU1007 2017-02-22 19:55',
  'SU1213 2017-04-13 18:05'],
 '3663 646985': ['SU1397 2017-02-24 06:05', 'SU1533 2017-02-05 08:15'],
 '8692 668325': ['SU1397 2017-02-24 06:05'],
 '2488 060632': ['SU1397 2017-02-24 06:05'],
 '7255 780119': ['SU1439 2017-01-30 14:15'],
 '0566 115105': ['SU1409 2017-01-23 05:05',
  'SU1136 2017-10-07 08:55',
  'SU1351 2017-11-17 11:10'],
 '3143 702553': ['SU1409 2017-02-16 05:05',
  'SU1436 2017-02-14 07:00',
  'SU1457 2017-02-02 20:55'],
 '0417 014583': ['SU1280 2017-03-08 10:55',
  'SU1052 2017-01-25 08:25',
  'SU1642 2017-02-01 08:40',
  'SU1175 2017-02-27 19:50'],
 '9474 654931': ['SU1235 2017-03-25 06:25', 'SU1230 2017-03-18 06:25'],
 '4260 590460': ['SU1253 2017-01-18 18:00',
  'SU1253 2017-02-02 17:40',
  'SU1392 2017-12-03 11:50',
  'SU1058 2017-01-12 15:25'],
 '7529 414902': ['SU1253 2017-01-18 18:00'],
 '4145 670833': ['SU1479 2017-04-21 09:55',
  'SU1478 2017-03-18 00:10',
  'SU1196 2017-05-18 22:50',
  'SU1279 2017-05-30 07:00'],
 '4478 046214': ['SU1639 2017-04-29 08:30'],
 '0521 187308': ['SU4605 2017-01-29 14:20',
  'SU5684 2017-02-24 10:30',
  'SU4606 2017-02-23 12:10'],
 '7601 558962': ['SU4605 2017-01-29 14:20',
  'SU5628 2017-05-13 14:00',
  'SU5685 2017-01-26 16:45'],
 '9657 311664': ['SU1434 2017-02-13 06:40',
  'SU1255 2017-01-09 11:10',
  'SU1429 2017-02-14 06:20'],
 '8003 630400': ['SU1434 2017-02-13 06:40',
  'SU1125 2017-02-09 17:10',
  'SU1009 2017-04-27 03:50',
  'SU1435 2017-03-02 13:15'],
 '2549 580581': ['SU1434 2017-02-13 06:40', 'SU1429 2017-02-19 06:20'],
 '4283 657983': ['SU1419 2017-06-22 15:30',
  'SU1159 2017-01-03 09:30',
  'SU1703 2017-12-17 14:00',
  'SU1702 2017-12-11 19:45',
  'SU1322 2017-08-30 21:25'],
 '1980 332676': ['SU5605 2017-02-19 11:10',
  'SU5624 2017-02-18 20:20',
  'SU5613 2017-01-10 15:50',
  'SU5640 2017-02-05 20:30',
  'SU5610 2017-02-23 10:25'],
 '1723 617716': ['SU1008 2017-08-17 20:00', 'SU1001 2017-08-22 09:15'],
 '7095 892328': ['SU4599 2017-02-28 09:00',
  'SU4600 2017-03-01 13:05',
  'SU6284 2017-04-24 11:45',
  'SU5604 2017-04-09 07:00',
  'SU5601 2017-03-06 19:00'],
 '2119 816401': ['SU4599 2017-02-28 09:00',
  'SU4600 2017-03-01 13:05',
  'SU4600 2017-02-13 13:05'],
 '9197 391701': ['SU4599 2017-02-28 09:00',
  'SU5618 2017-02-07 05:40',
  'SU5617 2017-01-01 09:45',
  'SU4600 2017-03-25 13:05',
  'SU1441 2017-05-14 05:40'],
 '2957 148469': ['SU4599 2017-02-28 09:00',
  'SU4600 2017-04-08 13:05',
  'SU4606 2017-02-25 12:10',
  'SU4600 2017-01-16 13:05'],
 '2456 752243': ['SU4599 2017-02-28 09:00',
  'SU5614 2017-04-04 07:30',
  'SU5621 2017-02-13 08:05',
  'SU5622 2017-02-04 19:45',
  'SU5643 2017-01-18 22:55',
  'SU1104 2017-04-24 13:20',
  'SU4600 2017-03-02 13:05',
  'SU5617 2017-04-10 09:45',
  'SU5619 2017-03-04 00:10'],
 '8547 706274': ['SU6286 2017-01-06 16:30',
  'SU1260 2017-04-06 16:55',
  'SU1337 2017-02-03 21:10',
  'SU1383 2017-01-02 06:40',
  'SU1439 2017-05-01 14:15',
  'SU1730 2017-01-04 16:00'],
 '0494 302487': ['SU6286 2017-01-06 16:30',
  'SU1439 2017-03-08 14:15',
  'SU1258 2017-02-27 15:00'],
 '1237 262759': ['SU6286 2017-01-06 16:30'],
 '0014 287508': ['SU6286 2017-01-06 16:30'],
 '4002 262543': ['SU6286 2017-01-06 16:30',
  'SU1206 2017-01-08 00:15',
  'SU1207 2017-03-24 03:55'],
 '7039 733246': ['SU6286 2017-01-06 16:30'],
 '4161 563066': ['SU1371 2017-02-02 12:35', 'SU1462 2017-12-01 06:05'],
 '2671 607187': ['SU1371 2017-02-02 12:35'],
 '1544 484128': ['SU1371 2017-02-02 12:35'],
 '2432 487686': ['SU1371 2017-02-02 12:35'],
 '0727 100652': ['SU1371 2017-02-02 12:35',
  'SU1372 2017-11-06 00:05',
  'SU1432 2017-02-04 09:25',
  'SU1433 2017-03-02 19:55'],
 '8407 105536': ['SU1371 2017-02-02 12:35',
  'SU4599 2017-03-24 09:00',
  'SU5603 2017-04-23 08:00',
  'SU4601 2017-04-27 10:20',
  'SU4600 2017-03-29 13:05',
  'SU4602 2017-05-01 13:10',
  'SU6287 2017-03-17 17:40',
  'SU5618 2017-05-03 05:40'],
 '5425 444990': ['SU1371 2017-02-02 12:35', 'SU1501 2017-01-09 14:30'],
 '1249 137079': ['SU1134 2017-01-09 09:30', 'SU1175 2017-01-08 19:50'],
 '9651 115076': ['SU1134 2017-01-09 09:30'],
 '2632 086503': ['SU1143 2017-04-18 17:55',
  'SU1390 2017-01-29 07:45',
  'SU1144 2017-04-01 17:15',
  'SU1391 2017-01-30 10:45',
  'SU1211 2017-01-05 12:35'],
 '8662 021782': ['SU5627 2017-01-08 11:40',
  'SU5628 2017-01-13 14:00',
  'SU5623 2017-02-02 19:25'],
 '8775 169530': ['SU5627 2017-01-08 11:40'],
 '2637 442781': ['SU1157 2017-04-10 16:00',
  'SU4605 2017-01-05 14:20',
  'SU5603 2017-01-29 08:00'],
 '1936 727798': ['SU1276 2017-08-22 07:15'],
 '6566 222714': ['SU1537 2017-03-16 10:40'],
 '2082 642956': ['SU1537 2017-03-16 10:40',
  'SU1445 2017-02-13 19:40',
  'SU1530 2017-02-25 21:25'],
 '1676 706778': ['SU1279 2017-03-05 07:00',
  'SU1280 2017-02-19 10:55',
  'SU1183 2017-01-15 18:20'],
 '9297 689788': ['SU1411 2017-03-09 11:15',
  'SU1402 2017-03-07 12:00',
  'SU4600 2017-01-04 13:05',
  'SU1406 2017-04-16 20:25',
  'SU5640 2017-01-30 20:30'],
 '0526 293376': ['SU1217 2017-01-08 06:05',
  'SU1416 2017-01-13 22:05',
  'SU1172 2017-02-11 21:25',
  'SU1252 2017-03-16 14:05',
  'SU1403 2017-01-16 17:25'],
 '3163 431667': ['SU1217 2017-01-08 06:05',
  'SU1141 2017-02-12 21:05',
  'SU1120 2017-01-27 00:40'],
 '9539 515805': ['SU1217 2017-01-08 06:05'],
 '7536 277407': ['SU1217 2017-01-08 06:05'],
 '8269 212723': ['SU1183 2017-01-30 18:20'],
 '4055 573903': ['SU1183 2017-01-30 18:20',
  'SU1247 2017-02-20 11:15',
  'SU1188 2017-01-18 10:15',
  'SU1211 2017-01-05 12:35'],
 '5220 087185': ['SU1546 2017-03-04 07:20',
  'SU1363 2017-05-02 20:35',
  'SU1356 2017-03-29 06:05',
  'SU1255 2017-02-19 11:10'],
 '9071 125153': ['SU1429 2017-05-06 06:20',
  'SU1434 2017-04-13 06:40',
  'SU1350 2017-05-25 08:00',
  'SU1351 2017-06-12 11:10'],
 '0443 548395': ['SU1356 2017-02-16 06:05', 'SU1361 2017-02-27 12:20'],
 '2833 087439': ['SU6184 2017-03-27 12:45', 'SU1409 2017-01-01 05:05'],
 '8003 198362': ['SU1643 2017-04-12 14:00',
  'SU1357 2017-05-28 10:05',
  'SU1190 2017-02-20 09:00',
  'SU1362 2017-04-20 16:50',
  'SU1642 2017-03-05 08:40',
  'SU1191 2017-03-01 12:20'],
 '1795 520260': ['SU5603 2017-03-06 08:00', 'SU4606 2017-01-05 12:10'],
 '5949 861963': ['SU1009 2017-05-05 03:50', 'SU1008 2017-03-07 20:00'],
 '0213 604722': ['SU1443 2017-03-16 09:55',
  'SU1417 2017-01-26 06:05',
  'SU5641 2017-02-20 23:10'],
 '3082 168198': ['SU1730 2017-06-14 16:00', 'SU5615 2017-08-22 14:05'],
 '4696 403442': ['SU1639 2017-03-17 08:30'],
 '7772 334828': ['SU1639 2017-03-17 08:30'],
 '7301 416373': ['SU1415 2017-05-04 22:10',
  'SU1460 2017-07-08 08:20',
  'SU6172 2017-08-31 07:15',
  'SU1356 2017-07-18 06:05',
  'SU1333 2017-04-10 13:00',
  'SU1406 2017-04-18 20:25',
  'SU1357 2017-08-05 10:05'],
 '1367 209053': ['SU4601 2017-08-11 10:20', 'SU4602 2017-09-08 13:10'],
 '6096 934457': ['SU1253 2017-01-21 17:40'],
 '8062 336992': ['SU1253 2017-01-21 17:40',
  'SU1407 2017-03-25 07:30',
  'SU1406 2017-02-22 20:25'],
 '1621 845600': ['SU1253 2017-01-21 17:40'],
 '3542 349342': ['SU1403 2017-01-10 17:25'],
 '4561 279121': ['SU1403 2017-01-10 17:25'],
 '7294 744915': ['SU1403 2017-01-10 17:25',
  'SU1322 2017-06-25 21:25',
  'SU1325 2017-07-04 19:15'],
 '4820 865551': ['SU1403 2017-01-10 17:25'],
 '6646 304904': ['SU4605 2017-07-31 14:20',
  'SU4600 2017-03-01 13:05',
  'SU5652 2017-01-09 21:40',
  'SU5619 2017-09-17 00:10',
  'SU5653 2017-02-08 00:50',
  'SU4599 2017-03-02 09:00',
  'SU5643 2017-01-01 22:55',
  'SU4606 2017-08-13 12:10'],
 '9217 074991': ['SU1056 2017-09-08 20:55',
  'SU6169 2017-07-17 00:50',
  'SU1546 2017-09-28 07:20',
  'SU1105 2017-08-25 17:25',
  'SU1056 2017-10-24 20:55',
  'SU1057 2017-09-10 01:45',
  'SU1547 2017-10-18 11:35'],
 '9644 171612': ['SU1602 2017-04-10 05:55',
  'SU6184 2017-03-10 12:45',
  'SU1491 2017-01-05 13:20'],
 '6478 400366': ['SU6179 2017-05-04 06:20',
  'SU6286 2017-04-30 16:30',
  'SU4602 2017-02-19 13:10',
  'SU1135 2017-05-19 14:10'],
 '5764 659799': ['SU1164 2017-04-08 21:40',
  'SU1429 2017-01-26 06:20',
  'SU1357 2017-03-30 10:05',
  'SU1169 2017-05-03 21:00'],
 '7054 734091': ['SU1512 2017-02-12 00:40',
  'SU1142 2017-03-31 13:45',
  'SU1143 2017-07-15 17:55',
  'SU1333 2017-01-03 13:00',
  'SU1511 2017-03-01 03:30'],
 '6147 434435': ['SU1234 2017-02-22 00:20',
  'SU1638 2017-04-29 00:00',
  'SU1639 2017-05-18 08:30'],
 '6163 014449': ['SU1254 2017-06-09 07:30',
  'SU1239 2017-01-23 08:30',
  'SU1169 2017-08-17 21:00'],
 '5597 328412': ['SU1465 2017-04-02 16:40',
  'SU1493 2017-02-11 21:40',
  'SU1324 2017-02-02 14:40',
  'SU1359 2017-01-26 18:50'],
 '6511 216489': ['SU1191 2017-02-18 12:20',
  'SU1383 2017-01-09 06:40',
  'SU1190 2017-02-08 09:00'],
 '0915 926763': ['SU1191 2017-02-18 12:20',
  'SU1198 2017-01-26 22:40',
  'SU1763 2017-01-21 05:35'],
 '2249 612647': ['SU1168 2017-12-13 18:10', 'SU1416 2017-03-22 22:05'],
 '5302 629133': ['SU1337 2017-01-04 21:10'],
 '4003 321330': ['SU1337 2017-01-04 21:10', 'SU1486 2017-01-23 10:40'],
 '8238 564036': ['SU1337 2017-01-04 21:10'],
 '0107 083691': ['SU5629 2017-07-12 17:30',
  'SU1424 2017-02-06 00:35',
  'SU1533 2017-02-23 08:15',
  'SU1441 2017-01-02 05:40',
  'SU1238 2017-05-04 21:45'],
 '6723 247259': ['SU5616 2017-07-26 03:00',
  'SU6286 2017-07-31 16:30',
  'SU5605 2017-07-04 11:10'],
 '9140 679671': ['SU1406 2017-05-01 20:25', 'SU1769 2017-03-25 19:25'],
 '6273 669260': ['SU5652 2017-02-06 21:40',
  'SU5685 2017-01-06 16:45',
  'SU1523 2017-03-15 09:35'],
 '8512 852633': ['SU5652 2017-02-06 21:40',
  'SU5685 2017-02-05 16:45',
  'SU5653 2017-03-01 00:50'],
 '1958 458558': ['SU5652 2017-02-06 21:40',
  'SU4600 2017-01-23 13:05',
  'SU5653 2017-02-26 00:50'],
 '6440 928797': ['SU5652 2017-02-06 21:40',
  'SU4606 2017-01-22 12:10',
  'SU1445 2017-02-14 19:40'],
 '8350 647518': ['SU1165 2017-03-11 01:55', 'SU1513 2017-11-04 07:05'],
 '1930 782980': ['SU1165 2017-03-11 01:55'],
 '9573 490219': ['SU1536 2017-06-25 00:20',
  'SU1353 2017-01-08 06:05',
  'SU1537 2017-07-08 10:40'],
 '1816 697320': ['SU1421 2017-01-14 12:50',
  'SU1172 2017-03-23 21:25',
  'SU6183 2017-09-11 09:55',
  'SU1403 2017-08-15 17:25',
  'SU1175 2017-05-31 19:50',
  'SU1521 2017-08-17 17:20'],
 '8119 083739': ['SU1421 2017-01-14 12:50'],
 '9417 157338': ['SU1331 2017-03-24 18:45', 'SU1509 2017-01-01 06:25'],
 '6601 420372': ['SU1419 2017-01-16 15:30'],
 '0367 311565': ['SU1700 2017-10-02 15:10',
  'SU1325 2017-03-10 19:15',
  'SU1510 2017-04-01 21:05'],
 '4155 732589': ['SU1451 2017-08-27 06:55',
  'SU1501 2017-05-05 14:30',
  'SU1141 2017-09-16 21:05',
  'SU1500 2017-05-03 08:20',
  'SU1459 2017-01-22 08:05',
  'SU1456 2017-07-28 10:25',
  'SU1640 2017-03-02 07:00'],
 '8270 941791': ['SU1451 2017-08-27 06:55',
  'SU1450 2017-07-08 20:20',
  'SU1277 2017-04-01 10:50',
  'SU1195 2017-03-01 20:35',
  'SU1507 2017-05-02 19:05',
  'SU1502 2017-04-15 22:30',
  'SU1198 2017-02-19 22:40',
  'SU1127 2017-12-22 19:35'],
 '7586 486761': ['SU1361 2017-05-30 12:20',
  'SU1365 2017-08-03 19:45',
  'SU1375 2017-08-15 18:55',
  'SU1364 2017-07-03 16:30',
  'SU1206 2017-01-11 00:15',
  'SU1159 2017-01-06 09:30',
  'SU1394 2017-02-19 20:15',
  'SU1362 2017-05-23 16:50'],
 '8808 742907': ['SU1444 2017-06-10 06:35',
  'SU1443 2017-07-09 09:55',
  'SU1213 2017-06-09 18:05',
  'SU1214 2017-06-08 16:40',
  'SU1491 2017-09-25 13:20',
  'SU1490 2017-07-22 06:55'],

### Вычисляем пассажиров у которых больше одного полета

In [93]:
passenger_flights_more_one = {}

for key, value in passenger_flights.items():
    if len(value) > 1:
        passenger_flights_more_one[key] = value
        
passenger_flights_more_one

{'0078 271703': ['SU1281 2017-07-29 14:15', 'SU1235 2017-02-04 06:25'],
 '6948 339409': ['SU1501 2017-09-30 14:30',
  'SU1007 2017-08-30 19:55',
  'SU1491 2017-01-04 13:20'],
 '5298 581934': ['SU1513 2017-07-11 07:05',
  'SU1113 2017-04-25 03:35',
  'SU1479 2017-02-27 09:55'],
 '6788 402722': ['SU1217 2017-10-01 06:05',
  'SU1255 2017-03-08 11:10',
  'SU1491 2017-02-06 13:20'],
 '3668 753452': ['SU1431 2017-03-12 07:05', 'SU1143 2017-01-15 17:55'],
 '8634 167429': ['SU1167 2017-03-07 05:00',
  'SU1503 2017-04-13 04:25',
  'SU1437 2017-06-17 12:25',
  'SU1247 2017-05-14 11:15'],
 '3466 808546': ['SU1431 2017-06-07 07:05',
  'SU1481 2017-01-12 06:40',
  'SU1365 2017-04-28 19:45',
  'SU6180 2017-03-05 11:05'],
 '3616 692590': ['SU1641 2017-02-14 15:20',
  'SU1275 2017-04-08 05:30',
  'SU1247 2017-01-17 11:15'],
 '8663 357259': ['SU1181 2017-11-15 03:10', 'SU1247 2017-02-23 11:15'],
 '8306 644972': ['SU1261 2017-03-01 23:10', 'SU1479 2017-01-22 09:55'],
 '7948 851468': ['SU1261 2017-03-01 23:10', 'SU1641 2017-03-09 15:20'],
 '6468 393450': ['SU1403 2017-09-05 17:25',
  'SU1501 2017-04-25 14:30',
  'SU1161 2017-06-19 19:10',
  'SU1375 2017-01-05 18:55'],
 '8295 760019': ['SU1371 2017-01-31 12:35',
  'SU1413 2017-01-10 13:55',
  'SU1251 2017-05-10 02:50'],
 '8063 081529': ['SU1211 2017-04-19 12:35',
  'SU1531 2017-01-31 07:55',
  'SU1233 2017-01-13 19:15'],
 '7574 442722': ['SU1009 2017-07-17 03:50',
  'SU1053 2017-02-04 12:20',
  'SU1485 2017-06-26 09:05'],
 '4405 704644': ['SU1397 2017-01-31 06:05',
  'SU1445 2017-01-06 19:40',
  'SU1417 2017-09-18 06:05',
  'SU1425 2017-11-19 05:55'],
 '8794 083189': ['SU1191 2017-01-02 12:20',
  'SU1213 2017-04-28 18:05',
  'SU1135 2017-03-17 14:10',
  'SU1233 2017-09-01 19:15',
  'SU1157 2017-05-28 16:00'],
 '6401 005380': ['SU1135 2017-07-20 14:10', 'SU1058 2017-01-08 15:25'],
 '8316 706629': ['SU1053 2017-02-06 12:20', 'SU1161 2017-05-01 19:10'],
 '1997 276152': ['SU1053 2017-02-06 12:20', 'SU1371 2017-01-19 12:35'],
 '1883 098614': ['SU1053 2017-02-06 12:20', 'SU6290 2017-01-14 14:30'],
 '0400 782744': ['SU1459 2017-01-13 08:05', 'SU1523 2017-06-17 09:35'],
 '3276 602860': ['SU1459 2017-01-13 08:05', 'SU1197 2017-03-17 02:45'],
 '1808 822155': ['SU1459 2017-01-13 08:05', 'SU6180 2017-03-09 11:05'],
 '5524 738294': ['SU1459 2017-01-13 08:05', 'SU1143 2017-05-15 17:55'],
 '0735 568732': ['SU1459 2017-01-13 08:05', 'SU1307 2017-05-15 10:15'],
 '8026 996881': ['SU1459 2017-01-13 08:05', 'SU1487 2017-01-19 21:35'],
 '0550 572974': ['SU1459 2017-01-13 08:05',
  'SU1129 2017-04-01 06:20',
  'SU1515 2017-03-02 14:00'],
 '6252 079751': ['SU1459 2017-01-13 08:05', 'SU1121 2017-02-28 15:40'],
 '6735 613581': ['SU1459 2017-01-13 08:05', 'SU1219 2017-02-13 06:25'],
 '3119 061454': ['SU1307 2017-03-22 10:15', 'SU1643 2017-03-02 14:00'],
 '3384 131110': ['SU1307 2017-03-22 10:15', 'SU1191 2017-02-24 12:20'],
 '3663 646985': ['SU1397 2017-02-24 06:05', 'SU1533 2017-02-05 08:15'],
 '0566 115105': ['SU1409 2017-01-23 05:05', 'SU1351 2017-11-17 11:10'],
 '3143 702553': ['SU1409 2017-02-16 05:05', 'SU1457 2017-02-02 20:55'],
 '4145 670833': ['SU1479 2017-04-21 09:55', 'SU1279 2017-05-30 07:00'],
 '4283 657983': ['SU1419 2017-06-22 15:30',
  'SU1159 2017-01-03 09:30',
  'SU1703 2017-12-17 14:00'],
 '8547 706274': ['SU6286 2017-01-06 16:30',
  'SU1337 2017-02-03 21:10',
  'SU1383 2017-01-02 06:40',
  'SU1439 2017-05-01 14:15'],
 '0494 302487': ['SU6286 2017-01-06 16:30', 'SU1439 2017-03-08 14:15'],
 '4002 262543': ['SU6286 2017-01-06 16:30', 'SU1207 2017-03-24 03:55'],
 '0727 100652': ['SU1371 2017-02-02 12:35', 'SU1433 2017-03-02 19:55'],
 '5425 444990': ['SU1371 2017-02-02 12:35', 'SU1501 2017-01-09 14:30'],
 '2632 086503': ['SU1143 2017-04-18 17:55',
  'SU1391 2017-01-30 10:45',
  'SU1211 2017-01-05 12:35'],
 '2082 642956': ['SU1537 2017-03-16 10:40', 'SU1445 2017-02-13 19:40'],
 '1676 706778': ['SU1279 2017-03-05 07:00', 'SU1183 2017-01-15 18:20'],
 '0526 293376': ['SU1217 2017-01-08 06:05', 'SU1403 2017-01-16 17:25'],
 '3163 431667': ['SU1217 2017-01-08 06:05', 'SU1141 2017-02-12 21:05'],
 '4055 573903': ['SU1183 2017-01-30 18:20',
  'SU1247 2017-02-20 11:15',
  'SU1211 2017-01-05 12:35'],
 '9071 125153': ['SU1429 2017-05-06 06:20', 'SU1351 2017-06-12 11:10'],
 '2833 087439': ['SU6184 2017-03-27 12:45', 'SU1409 2017-01-01 05:05'],
 '8003 198362': ['SU1643 2017-04-12 14:00',
  'SU1357 2017-05-28 10:05',
  'SU1191 2017-03-01 12:20'],
 '0213 604722': ['SU1443 2017-03-16 09:55', 'SU1417 2017-01-26 06:05'],
 '7301 416373': ['SU1415 2017-05-04 22:10',
  'SU6172 2017-08-31 07:15',
  'SU1333 2017-04-10 13:00',
  'SU1357 2017-08-05 10:05'],
 '8062 336992': ['SU1253 2017-01-21 17:40', 'SU1407 2017-03-25 07:30'],
 '7294 744915': ['SU1403 2017-01-10 17:25', 'SU1325 2017-07-04 19:15'],
 '5597 328412': ['SU1465 2017-04-02 16:40',
  'SU1493 2017-02-11 21:40',
  'SU1359 2017-01-26 18:50'],
 '6511 216489': ['SU1191 2017-02-18 12:20', 'SU1383 2017-01-09 06:40'],
 '0915 926763': ['SU1191 2017-02-18 12:20', 'SU1763 2017-01-21 05:35'],
 '8350 647518': ['SU1165 2017-03-11 01:55', 'SU1513 2017-11-04 07:05'],
 '1816 697320': ['SU1421 2017-01-14 12:50',
  'SU1403 2017-08-15 17:25',
  'SU1175 2017-05-31 19:50'],
 '9417 157338': ['SU1331 2017-03-24 18:45', 'SU1509 2017-01-01 06:25'],
 '4155 732589': ['SU1451 2017-08-27 06:55',
  'SU1501 2017-05-05 14:30',
  'SU1141 2017-09-16 21:05',
  'SU1459 2017-01-22 08:05'],
 '8270 941791': ['SU1451 2017-08-27 06:55',
  'SU1277 2017-04-01 10:50',
  'SU1195 2017-03-01 20:35',
  'SU1507 2017-05-02 19:05',
  'SU1127 2017-12-22 19:35'],
 '7586 486761': ['SU1361 2017-05-30 12:20',
  'SU1365 2017-08-03 19:45',
  'SU1375 2017-08-15 18:55',
  'SU1159 2017-01-06 09:30'],
 '4792 100994': ['SU1403 2017-04-27 17:25', 'SU1371 2017-01-06 12:35'],
 '9681 718168': ['SU1403 2017-04-27 17:25', 'SU1393 2017-06-20 22:05'],
 '6775 533308': ['SU1135 2017-02-12 14:10', 'SU1639 2017-01-15 08:30'],
 '3908 966440': ['SU1769 2017-02-05 19:25', 'SU1125 2017-01-13 17:10'],
 '3234 037254': ['SU1769 2017-02-05 19:25', 'SU1537 2017-04-01 10:40'],
 '2660 056731': ['SU1461 2017-01-10 18:30', 'SU1109 2017-06-21 07:30'],
 '6793 521613': ['SU1461 2017-01-10 18:30', 'SU1409 2017-12-28 05:05'],
 '4221 293019': ['SU1461 2017-01-10 18:30', 'SU1323 2017-02-14 02:15'],
 '0460 208247': ['SU1535 2017-03-17 21:15', 'SU1053 2017-01-23 12:20'],
 '9800 130261': ['SU1357 2017-05-10 10:05',
  'SU1535 2017-01-03 21:15',
  'SU1641 2017-02-04 15:20',
  'SU1763 2017-03-08 05:35'],
 '2473 462695': ['SU1175 2017-09-22 19:50',
  'SU1271 2017-08-05 09:25',
  'SU1459 2017-01-15 08:05'],
 '3882 145761': ['SU1237 2017-05-09 09:35',
  'SU1463 2017-01-26 16:20',
  'SU1279 2017-06-11 07:00'],
 '9862 659143': ['SU1521 2017-06-18 17:20',
  'SU6172 2017-06-07 07:15',
  'SU1537 2017-05-31 10:40'],
 '8265 805182': ['SU1515 2017-03-20 14:00', 'SU1513 2017-01-25 07:05'],
 '4379 179946': ['SU1515 2017-03-20 14:00',
  'SU1131 2017-06-17 02:40',
  'SU1641 2017-01-15 15:20'],
 '7164 579965': ['SU1515 2017-03-20 14:00', 'SU1463 2017-01-26 16:20'],
 '4570 374550': ['SU1053 2017-02-20 12:20', 'SU1145 2017-03-09 08:00'],
 '0773 260697': ['SU1307 2017-01-28 10:15', 'SU1239 2017-01-02 08:30'],
 '7009 307913': ['SU1121 2017-03-17 15:40',
  'SU1373 2017-03-31 02:55',
  'SU1131 2017-02-08 02:40'],
 '1268 847781': ['SU1437 2017-02-26 12:25', 'SU1201 2017-01-04 13:05'],
 '0224 275586': ['SU1355 2017-03-13 21:05', 'SU1175 2017-02-18 19:50'],
 '1794 449214': ['SU1251 2017-04-27 02:50',
  'SU1253 2017-02-02 17:40',
  'SU1435 2017-02-27 13:15'],
 '3423 018345': ['SU1351 2017-08-22 11:10', 'SU1059 2017-02-06 19:40'],
 '8231 603394': ['SU1501 2017-03-04 14:30',
  'SU1481 2017-02-21 06:40',
  'SU1521 2017-05-26 17:20'],
 '2360 941897': ['SU6172 2017-01-15 07:15', 'SU1135 2017-04-10 14:10'],
 '0511 868250': ['SU1397 2017-07-31 06:05',
  'SU1763 2017-01-12 05:35',
  'SU1233 2017-09-26 19:15'],
 '4517 455995': ['SU1457 2017-04-15 20:55', 'SU1357 2017-01-07 10:05'],
 '4163 394818': ['SU1001 2017-12-04 09:15',
  'SU1523 2017-01-13 09:35',
  'SU1277 2017-02-11 10:50',
  'SU1759 2017-07-20 12:35'],
 '5741 590053': ['SU1001 2017-12-04 09:15', 'SU1769 2017-01-17 19:25'],
 '5955 956193': ['SU1437 2017-03-19 12:25', 'SU1175 2017-01-07 19:50'],
 '9976 515130': ['SU1255 2017-03-11 11:10', 'SU1363 2017-01-01 20:35'],
 '6379 957375': ['SU1255 2017-03-11 11:10', 'SU1515 2017-01-05 14:00'],
 '1312 309480': ['SU1423 2017-01-09 19:30', 'SU1231 2017-02-08 12:30'],
 '9493 512557': ['SU1423 2017-01-09 19:30',
  'SU1141 2017-01-26 21:05',
  'SU1393 2017-04-23 22:05'],
 '4239 670634': ['SU1423 2017-01-09 19:30',
  'SU1487 2017-04-18 21:35',
  'SU1409 2017-08-12 05:05',
  'SU1215 2017-05-22 21:35',
  'SU1239 2017-10-07 08:30'],
 '8416 929389': ['SU1217 2017-01-03 06:05', 'SU1157 2017-01-30 16:00'],
 '3174 231529': ['SU1191 2017-03-10 12:20', 'SU1535 2017-01-05 21:15'],
 '3599 811271': ['SU1509 2017-03-24 06:25', 'SU1183 2017-02-19 18:20'],
 '6237 434853': ['SU1191 2017-01-17 12:20', 'SU1233 2017-02-18 19:15'],
 '6925 372539': ['SU1191 2017-01-17 12:20', 'SU1173 2017-01-02 06:00'],
 '2754 979774': ['SU1191 2017-01-17 12:20', 'SU1363 2017-01-26 20:35'],
 '8360 229939': ['SU1181 2017-02-24 03:10',
  'SU1181 2017-04-13 03:10',
  'SU1359 2017-03-26 18:50'],
 '3203 792804': ['SU1181 2017-02-24 03:10', 'SU1437 2017-01-08 12:25'],
 '8479 370130': ['SU1353 2017-01-06 06:05',
  'SU1167 2017-02-04 05:00',
  'SU1056 2017-02-14 22:05'],
 '4240 002267': ['SU1353 2017-01-06 06:05', 'SU1145 2017-02-01 08:00'],
 '4126 489378': ['SU1335 2017-04-13 02:50',
  'SU1253 2017-01-30 17:40',
  'SU1415 2017-01-04 22:10'],
 '0842 545376': ['SU1335 2017-04-13 02:50',
  'SU1493 2017-07-28 21:40',
  'SU1403 2017-05-14 17:25'],
 '1223 596716': ['SU1335 2017-04-13 02:50', 'SU1491 2017-02-11 13:20'],
 '6416 324969': ['SU1437 2017-04-16 12:25', 'SU1205 2017-01-03 23:05'],
 '2315 174721': ['SU1365 2017-03-22 19:45', 'SU1509 2017-02-02 06:25'],
 '4335 690124': ['SU1437 2017-11-14 12:25',
  'SU1193 2017-07-02 18:05',
  'SU1479 2017-02-14 09:55',
  'SU1373 2017-09-28 02:55'],
 '2908 898279': ['SU1759 2017-10-29 12:35',
  'SU1005 2017-08-29 16:00',
  'SU1521 2017-12-07 17:20',
  'SU1125 2017-07-14 17:10'],
 '2509 713341': ['SU1463 2017-05-01 16:20', 'SU1443 2017-03-03 09:55'],
 '7100 615061': ['SU1463 2017-05-01 16:20', 'SU1125 2017-07-11 17:10'],
 '3762 228036': ['SU1501 2017-03-09 14:30',
  'SU1173 2017-01-07 06:00',
  'SU1537 2017-03-23 10:40'],
 '1970 806018': ['SU1409 2017-12-26 05:05',
  'SU1459 2017-01-01 08:05',
  'SU1183 2017-12-11 18:20'],
 '9147 800780': ['SU1361 2017-06-08 12:20', 'SU1123 2017-01-19 12:45'],
 '7698 288357': ['SU1503 2017-04-10 04:25',
  'SU1261 2017-04-27 23:10',
  'SU1465 2017-01-21 16:40',
  'SU1415 2017-03-08 22:10'],
 '0516 632518': ['SU1429 2017-11-22 06:20',
  'SU1261 2017-05-18 23:10',
  'SU1363 2017-03-05 20:35',
  'SU1363 2017-09-26 20:35'],
 '1301 580117': ['SU1355 2017-08-28 21:05', 'SU1437 2017-12-30 12:25'],
 '5065 959261': ['SU1479 2017-01-17 09:55',
  'SU1371 2017-08-31 12:35',
  'SU1463 2017-03-16 16:20'],
 '7866 635561': ['SU1479 2017-01-17 09:55',
  'SU1145 2017-06-20 08:00',
  'SU1255 2017-11-03 11:10',
  'SU1459 2017-08-03 08:05'],
 '7577 647136': ['SU1407 2017-03-09 07:30', 'SU1479 2017-01-02 09:55'],
 '3947 540039': ['SU1407 2017-03-09 07:30', 'SU1603 2017-01-19 10:50'],
 '5661 526791': ['SU1513 2017-01-02 07:05', 'SU1219 2017-02-10 06:25'],
 '0755 914732': ['SU1513 2017-01-02 07:05', 'SU1259 2017-06-05 21:00'],
 '5822 908870': ['SU1513 2017-01-02 07:05', 'SU1435 2017-02-08 13:15'],
 '1238 862282': ['SU1135 2017-01-30 14:10', 'SU1507 2017-05-07 19:05'],
 '6052 058675': ['SU1407 2017-01-23 07:30', 'SU1159 2017-02-05 09:30'],
 '1167 961739': ['SU1191 2017-06-25 12:20',
  'SU1195 2017-07-26 20:35',
  'SU1731 2017-06-10 13:25'],
 '2201 742395': ['SU1417 2017-02-08 06:05', 'SU1479 2017-01-08 09:55'],
 '2952 078841': ['SU1417 2017-02-08 06:05',
  'SU1351 2017-03-17 11:10',
  'SU1325 2017-03-20 19:15'],
 '8267 769738': ['SU1417 2017-02-08 06:05',
  'SU1491 2017-09-18 13:20',
  'SU1307 2017-03-08 10:15'],
 '7639 968824': ['SU1417 2017-02-08 06:05',
  'SU1215 2017-04-13 21:35',
  'SU1183 2017-01-04 18:20',
  'SU1205 2017-02-18 23:05'],
 '5478 184764': ['SU1003 2017-11-21 12:45',
  'SU1201 2017-08-27 13:05',
  'SU1507 2017-01-01 19:05'],
 '7575 446337': ['SU1485 2017-01-07 09:05', 'SU1429 2017-03-04 06:20'],
 '1714 220710': ['SU1485 2017-01-07 09:05',
  'SU1201 2017-01-17 13:05',
  'SU1547 2017-07-03 11:35'],
 '9226 856073': ['SU1409 2017-01-02 05:05', 'SU6286 2017-01-26 16:30'],
 '5191 574835': ['SU1109 2017-01-05 07:30', 'SU1251 2017-05-25 02:50'],
 '2416 218366': ['SU1411 2017-01-11 11:15', 'SU1173 2017-06-08 06:00'],
 '9723 350552': ['SU1411 2017-01-11 11:15', 'SU1463 2017-01-02 16:20'],
 '3332 414902': ['SU1563 2017-08-22 13:05',
  'SU1511 2017-04-19 03:30',
  'SU1537 2017-01-05 10:40'],
 '6487 702633': ['SU1247 2017-01-18 11:15', 'SU1491 2017-01-05 13:20'],
 '3286 956062': ['SU1247 2017-01-18 11:15',
  'SU1365 2017-02-14 19:45',
  'SU1137 2017-07-31 13:20',
  'SU1259 2017-06-03 21:00'],
 '1868 120965': ['SU1009 2017-01-29 03:50', 'SU1713 2017-06-18 14:40'],
 '9705 416323': ['SU1763 2017-02-21 05:35',
  'SU1371 2017-01-16 12:35',
  'SU1431 2017-01-01 07:05',
  'SU1331 2017-03-12 18:45'],
 '6078 939250': ['SU1183 2017-02-24 18:20', 'SU1419 2017-02-20 15:30'],
 '7077 241017': ['SU1195 2017-10-27 20:35', 'SU1731 2017-05-01 13:25'],
 '3865 366564': ['SU1219 2017-01-31 06:25',
  'SU1281 2017-02-14 14:15',
  'SU1137 2017-01-05 13:20'],
 '8587 421171': ['SU1109 2017-02-05 07:30', 'SU1465 2017-01-12 16:40'],
 '2471 172685': ['SU1109 2017-02-05 07:30', 'SU1769 2017-03-20 19:25'],
 '0480 513917': ['SU1431 2017-04-11 07:05', 'SU1435 2017-06-13 13:15'],
 '1932 260126': ['SU1431 2017-04-11 07:05',
  'SU1113 2017-06-20 03:35',
  'SU1395 2017-09-10 07:30'],
 '3219 247974': ['SU1009 2017-10-08 03:50',
  'SU1405 2017-06-08 20:15',
  'SU1393 2017-01-06 22:05',
  'SU1139 2017-05-19 09:50',
  'SU1367 2017-06-06 12:45',
  'SU1277 2017-11-23 10:50'],
 '0092 454418': ['SU1219 2017-03-31 06:25',
  'SU1493 2017-06-25 21:40',
  'SU1285 2017-07-29 09:50',
  'SU1145 2018-01-01 08:00'],
 '3902 680890': ['SU1255 2017-09-25 11:10',
  'SU1443 2017-01-13 09:55',
  'SU1058 2017-01-18 15:25'],
 '1833 927488': ['SU1391 2017-01-04 10:45', 'SU1253 2017-01-27 17:40'],
 '9316 210150': ['SU1391 2017-01-04 10:45', 'SU1515 2017-08-09 14:00'],
 '3297 856575': ['SU1391 2017-01-04 10:45', 'SU1239 2017-02-19 08:30'],
 '3250 659639': ['SU1431 2017-02-01 07:05', 'SU1371 2017-05-02 12:35'],
 '0831 664292': ['SU1431 2017-02-01 07:05',
  'SU1431 2017-08-31 07:05',
  'SU1207 2017-04-02 03:55'],
 '4742 188132': ['SU1431 2017-02-01 07:05',
  'SU6182 2017-05-06 21:50',
  'SU1173 2017-06-16 06:00'],
 '2750 236892': ['SU1183 2017-01-03 18:20', 'SU1059 2017-02-06 19:40'],
 '1853 883763': ['SU1513 2017-03-07 07:05',
  'SU1443 2017-01-01 09:55',
  'SU1501 2017-07-04 14:30',
  'SU1321 2017-08-18 13:10'],
 '4175 522229': ['SU1459 2017-09-13 08:05', 'SU1213 2017-05-25 18:05'],
 '6687 201169': ['SU1435 2017-04-18 13:15', 'SU1255 2017-01-10 11:10'],
 '1957 307867': ['SU1531 2017-01-10 07:55', 'SU1275 2017-01-29 05:30'],
 '2560 373656': ['SU1531 2017-01-10 07:55',
  'SU1273 2017-04-04 11:15',
  'SU1409 2017-08-28 05:05'],
 '8507 580964': ['SU1531 2017-01-10 07:55', 'SU1459 2017-02-21 08:05'],
 '6027 606755': ['SU1531 2017-01-10 07:55', 'SU1197 2017-03-30 02:45'],
 '9333 498951': ['SU1463 2017-04-08 16:20',
  'SU1549 2017-01-05 06:25',
  'SU1193 2017-02-14 18:05',
  'SU1217 2017-07-28 06:05',
  'SU1169 2017-01-26 21:00'],
 '0853 916165': ['SU1205 2017-04-21 23:05', 'SU1465 2017-01-16 16:40'],
 '1255 434884': ['SU1369 2017-01-22 06:05', 'SU1491 2017-01-15 13:20'],
 '6344 406187': ['SU1461 2017-05-06 18:30',
  'SU1485 2017-02-24 09:05',
  'SU1363 2017-01-04 20:35'],
 '2710 652901': ['SU1461 2017-05-06 18:30', 'SU1195 2017-04-05 20:35'],
 '6617 739571': ['SU1461 2017-05-06 18:30',
  'SU1369 2017-02-18 06:05',
  'SU1491 2017-05-29 13:20',
  'SU1487 2017-06-20 21:35'],
 '0959 301754': ['SU1207 2017-04-28 03:55',
  'SU1279 2017-02-12 07:00',
  'SU1157 2017-11-14 16:00'],
 '9584 313919': ['SU1275 2017-03-25 05:30',
  'SU1233 2017-07-04 19:15',
  'SU1431 2017-01-08 07:05'],
 '5880 327886': ['SU1413 2017-03-02 13:55',
  'SU1641 2017-01-19 15:20',
  'SU1479 2017-01-01 09:55'],
 '6177 668167': ['SU6288 2017-05-04 11:30',
  'SU1165 2017-01-17 01:55',
  'SU1437 2017-10-20 12:25'],
 '7910 624362': ['SU1509 2017-01-20 06:25',
  'SU1167 2017-06-16 05:00',
  'SU1219 2017-12-17 06:25'],
 '3041 680633': ['SU1131 2017-05-18 02:40',
  'SU1423 2017-04-18 19:30',
  'SU1435 2017-01-28 13:15',
  'SU1135 2017-06-10 14:10'],
 '7826 291764': ['SU1231 2017-06-20 12:30',
  'SU1191 2017-04-24 12:20',
  'SU1395 2017-05-05 07:30'],
 '4981 046083': ['SU1231 2017-06-20 12:30', 'SU1213 2017-03-07 18:05'],
 '8920 116974': ['SU1759 2017-07-09 12:35',
  'SU1703 2017-03-18 14:00',
  'SU1421 2017-04-03 12:50'],
 '5379 559303': ['SU1391 2017-02-21 10:45', 'SU1535 2017-02-28 21:15'],
 '5181 656775': ['SU1335 2017-03-24 02:50', 'SU6182 2017-06-16 21:50'],
 '8215 063708': ['SU1365 2017-03-14 19:45',
  'SU1321 2017-01-28 13:10',
  'SU1173 2017-01-01 06:00',
  'SU1139 2017-02-18 09:50'],
 '7729 530455': ['SU1161 2017-01-04 19:10', 'SU1189 2017-09-24 14:55'],
 '8630 838124': ['SU1375 2017-01-27 18:55', 'SU1535 2017-01-05 21:15'],
 '3329 782945': ['SU1129 2017-03-10 06:20', 'SU1479 2017-01-07 09:55'],
 '7404 179526': ['SU1509 2017-09-06 06:25',
  'SU1363 2017-03-23 20:35',
  'SU6170 2017-12-03 05:05',
  'SU6284 2017-02-18 11:45'],
 '8329 265263': ['SU1195 2017-04-03 20:35',
  'SU1367 2017-01-18 12:45',
  'SU1465 2017-07-04 16:40'],
 '9108 882308': ['SU1371 2017-03-24 12:35',
  'SU1145 2017-05-16 08:00',
  'SU1367 2017-05-04 12:45'],
 '5198 101734': ['SU1425 2017-01-05 05:55', 'SU1253 2017-01-12 17:40'],
 '9711 454857': ['SU1425 2017-01-05 05:55',
  'SU1393 2017-04-06 22:05',
  'SU1369 2017-02-26 06:05'],
 '8211 661471': ['SU1425 2017-01-05 05:55', 'SU1537 2017-02-07 10:40'],
 '0748 201470': ['SU1195 2017-02-02 20:35', 'SU1145 2017-01-03 08:00'],
 '3711 099110': ['SU1195 2017-02-02 20:35', 'SU6290 2017-01-12 14:30'],
 '5841 531429': ['SU1279 2017-09-06 07:00', 'SU1173 2017-01-04 06:00'],
 '1776 620632': ['SU1205 2017-01-04 23:05', 'SU1457 2017-08-27 20:55'],
 '2589 407749': ['SU1009 2017-04-07 03:50', 'SU1713 2017-02-20 14:40'],
 '2519 732583': ['SU1443 2017-02-25 09:55', 'SU1167 2017-03-20 05:00'],
 '7531 706115': ['SU1353 2017-11-03 06:05', 'SU1353 2017-01-30 06:05'],
 '8376 211831': ['SU6170 2017-03-25 05:05',
  'SU1191 2017-06-14 12:20',
  'SU1275 2017-01-06 05:30'],
 '6909 245092': ['SU6170 2017-03-25 05:05', 'SU1427 2017-01-16 22:45'],
 '6119 683669': ['SU1207 2017-01-02 03:55', 'SU1521 2017-01-26 17:20'],
 '6115 450475': ['SU1207 2017-01-02 03:55',
  'SU1533 2017-05-10 08:15',
  'SU1487 2017-06-17 21:35'],
 '9357 527030': ['SU1487 2017-05-06 21:35', 'SU1423 2017-01-02 19:30'],
 '6944 524150': ['SU1217 2017-01-06 06:05', 'SU6180 2017-04-27 11:05'],
 '6082 307849': ['SU1445 2017-01-01 19:40', 'SU6180 2017-02-24 11:05'],
 '6759 003733': ['SU1445 2017-01-01 19:40', 'SU1481 2017-02-27 06:40'],
 '6785 928243': ['SU1285 2017-08-05 09:50',
  'SU1205 2017-12-26 23:05',
  'SU1351 2017-03-17 11:10'],
 '1455 087079': ['SU1167 2017-02-05 05:00', 'SU1363 2017-01-29 20:35'],
 '6953 034553': ['SU1167 2017-02-05 05:00',
  'SU1109 2017-05-05 07:30',
  'SU1425 2017-01-01 05:55'],
 '9760 187245': ['SU1207 2017-02-07 03:55', 'SU1139 2017-01-13 09:50'],
 '9214 133748': ['SU1481 2017-12-25 06:40', 'SU1481 2017-08-27 06:40'],
 '7960 962284': ['SU1185 2017-02-05 07:00', 'SU1205 2017-02-23 23:05'],
 '2338 196758': ['SU1185 2017-02-05 07:00', 'SU1643 2017-01-08 14:00'],
 '1710 130997': ['SU1185 2017-02-05 07:00',
  'SU1515 2017-06-19 14:00',
  'SU1563 2017-07-11 13:05',
  'SU1395 2017-01-15 07:30',
  'SU1515 2017-06-13 14:00'],
 '0705 594287': ['SU1375 2017-01-17 18:55', 'SU1435 2017-01-01 13:15'],

### Находим пассажиров, которые летали вместе

In [118]:
result_list = []

for doc, number in passenger_flights_more_one.items():
    for doc1, number1 in passenger_flights_more_one.items():
        if doc != doc1:
            intersect = set(number).intersection(set(number1))
            if len(intersect) > 1:
                first = str(df[df['PassengerDocument'] == doc]['PassengerLastName'].unique())
                second = str(df[df['PassengerDocument'] == doc1]['PassengerLastName'].unique())
                if first.strip()[:7] != second.strip()[:7]:
                    result_list.append([first, doc, second, doc1, intersect])
                    print(first, second)
                    print(doc, ':', doc1, ':', intersect)
                    print('-' * 20)

['GORELOV'] ['LEONOV']
7473 879825 : 2027 454777 : {'SU1145 2017-01-10 08:00', 'SU1383 2017-01-04 06:40'}
--------------------
['LEONOV'] ['GORELOV']
2027 454777 : 7473 879825 : {'SU1145 2017-01-10 08:00', 'SU1383 2017-01-04 06:40'}
--------------------

In [155]:
df2 = df[df['PassengerDocument'].isin(['7473 879825', '2027 454777'])]
df2 = df2[df2['FlightNumber_by_date'].isin(['SU1145 2017-01-10 08:00', 'SU1383 2017-01-04 06:40'])]
df2[['PassengerLastName', 'PassengerFirstName', 'PassengerSecondName', 'PassengerDocument', 'FlightNumber', 'FlightDate', 'FlightTime', 'Destination']]

,PassengerLastName,PassengerFirstName,PassengerSecondName,PassengerDocument,FlightNumber,FlightDate,FlightTime,Destination
35287,GORELOV,LEV,S.,7473 879825,SU1145,2017-01-10,08:00,Moscow
35289,LEONOV,ANDREI,MAKSIMOVICH,2027 454777,SU1145,2017-01-10,08:00,Moscow
72454,LEONOV,ANDREI,MAKSIMOVICH,2027 454777,SU1383,2017-01-04,06:40,Moscow
72475,GORELOV,LEV,SAVVOVICH,7473 879825,SU1383,2017-01-04,06:40,Moscow

In [156]:
df1 = df[df['PassengerDocument'].isin(['7473 879825', '2027 454777'])]
df1 = df1[~df1['FlightNumber_by_date'].isin(['SU1145 2017-01-10 08:00', 'SU1383 2017-01-04 06:40'])]
df1[['PassengerLastName', 'PassengerFirstName', 'PassengerSecondName', 'PassengerDocument', 'FlightNumber', 'FlightDate', 'FlightTime', 'Destination']]

,PassengerLastName,PassengerFirstName,PassengerSecondName,PassengerDocument,FlightNumber,FlightDate,FlightTime,Destination
34047,LEONOV,ANDREI,MAKSIMOVICH,2027 454777,SU1144,2017-01-08,17:15,Anapa
151810,GORELOV,LEV,SAVVOVICH,7473 879825,SU1144,2017-01-05,17:15,Anapa